@echo off
call CardSim-settings.cmd
java -jar GTCardSimCtrl.jar -w %GT_WORKSPACE% -is "GT Scripts ePA EAC2 Reader BSI/testsuites/Data/Test Object Terminal Software/Terminal Authentication/TS_TA_1.2.1/TS_TA_1.2.1_a/CERTS.IS" -at "GT Scripts ePA EAC2 Reader BSI/testsuites/Data/Test Object Terminal Software/Terminal Authentication/TS_TA_1.2.1/TS_TA_1.2.1_a/CERTS.AT" -fileAdd "a" -p %CERT_DIR%\\CERT_CV_CVCA_U_TS_TA_1_2_1_a.cvcert %DATE%
java -jar GTCardSimCtrl.jar -w %GT_WORKSPACE% -is "GT Scripts ePA EAC2 Reader BSI/testsuites/Data/Test Object Terminal Software/Terminal Authentication/TS_TA_1.2.1/TS_TA_1.2.1_b/CERTS.IS" -at "GT Scripts ePA EAC2 Reader BSI/testsuites/Data/Test Object Terminal Software/Terminal Authentication/TS_TA_1.2.1/TS_TA_1.2.1_b/CERTS.AT" -fileAdd "b" -p %CERT_DIR%\\CERT_CV_CVCA_U_TS_TA_1_2_1_b.cvcert %DATE%
java -jar GTCardSimCtrl.jar -w %GT_WORKSPACE% -is "GT Scripts ePA EAC2 Reader BSI/testsuites/Data/Test Object Terminal Software/Terminal Authentication/TS_TA_1.2.1/TS_TA_1.2.1_c/CERTS.IS" -at "GT Scripts ePA EAC2 Reader BSI/testsuites/Data/Test Object Terminal Software/Terminal Authentication/TS_TA_1.2.1/TS_TA_1.2.1_c/CERTS.AT" -fileAdd "c" -p %CERT_DIR%\\CERT_CV_CVCA_U_TS_TA_1_2_1_c.cvcert %DATE%
java -jar GTCardSimCtrl.jar -w %GT_WORKSPACE% -is "GT Scripts ePA EAC2 Reader BSI/testsuites/Data/Test Object Terminal Software/Terminal Authentication/TS_TA_1.2.1/TS_TA_1.2.1_d/CERTS.IS" -at "GT Scripts ePA EAC2 Reader BSI/testsuites/Data/Test Object Terminal Software/Terminal Authentication/TS_TA_1.2.1/TS_TA_1.2.1_d/CERTS.AT" -fileAdd "d" -p %CERT_DIR%\\CERT_CV_CVCA_U_TS_TA_1_2_1_d.cvcert %DATE%
java -jar GTCardSimCtrl.jar -w %GT_WORKSPACE% -is "GT Scripts ePA EAC2 Reader BSI/testsuites/Data/Test Object Terminal Software/Terminal Authentication/TS_TA_1.2.1/TS_TA_1.2.1_e/CERTS.IS" -at "GT Scripts ePA EAC2 Reader BSI/testsuites/Data/Test Object Terminal Software/Terminal Authentication/TS_TA_1.2.1/TS_TA_1.2.1_e/CERTS.AT" -fileAdd "e" -p %CERT_DIR%\\CERT_CV_CVCA_U_TS_TA_1_2_1_e.cvcert %DATE%
java -jar GTCardSimCtrl.jar -w %GT_WORKSPACE% -is "GT Scripts ePA EAC2 Reader BSI/testsuites/Data/Test Object Terminal Software/Terminal Authentication/TS_TA_1.2.1/TS_TA_1.2.1_f/CERTS.IS" -at "GT Scripts ePA EAC2 Reader BSI/testsuites/Data/Test Object Terminal Software/Terminal Authentication/TS_TA_1.2.1/TS_TA_1.2.1_f/CERTS.AT" -fileAdd "f" -p %CERT_DIR%\\CERT_CV_CVCA_U_TS_TA_1_2_1_f.cvcert %DATE%

java -jar GTCardSimCtrl.jar -w %GT_WORKSPACE% -is "GT Scripts ePA EAC2 Reader BSI/testsuites/Data/CFG.CERTS.TA/CFG.DFLT.EAC.IS" -at "GT Scripts ePA EAC2 Reader BSI/testsuites/Data/CFG.CERTS.TA/CFG.DFLT.EAC.AT" -p %CERT_DIR%\\CERT_CV_CVCA_1.cvcert %DATE%

pause