
package com.hjp.globaltester.control.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import net.java.dev.jaxb.array.ObjectFactory;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SimulatorControlSoapProxy", targetNamespace = "http://soap.control.globaltester.hjp.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SimulatorControlSoapProxy {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.control.globaltester.hjp.com/SimulatorControlSoapProxy/getStateRequest", output = "http://soap.control.globaltester.hjp.com/SimulatorControlSoapProxy/getStateResponse")
    public StringArray getState(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        StringArray arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.control.globaltester.hjp.com/SimulatorControlSoapProxy/updateStateRequest", output = "http://soap.control.globaltester.hjp.com/SimulatorControlSoapProxy/updateStateResponse")
    public boolean updateState(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        StringArray arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.control.globaltester.hjp.com/SimulatorControlSoapProxy/loadConfigurationRequest", output = "http://soap.control.globaltester.hjp.com/SimulatorControlSoapProxy/loadConfigurationResponse")
    public boolean loadConfiguration(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.control.globaltester.hjp.com/SimulatorControlSoapProxy/startSimulatorRequest", output = "http://soap.control.globaltester.hjp.com/SimulatorControlSoapProxy/startSimulatorResponse")
    public boolean startSimulator();

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.control.globaltester.hjp.com/SimulatorControlSoapProxy/stopSimulatorRequest", output = "http://soap.control.globaltester.hjp.com/SimulatorControlSoapProxy/stopSimulatorResponse")
    public boolean stopSimulator();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.control.globaltester.hjp.com/SimulatorControlSoapProxy/getErrorRequest", output = "http://soap.control.globaltester.hjp.com/SimulatorControlSoapProxy/getErrorResponse")
    public String getError();

}
