
package com.hjp.globaltester.control.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimulatorControlSoapProxyService", targetNamespace = "http://soap.control.globaltester.hjp.com/", wsdlLocation = "http://localhost:8888/globaltester/simulatorSampleService?wsdl")
public class SimulatorControlSoapProxyService
    extends Service
{

    private final static URL SIMULATORCONTROLSOAPPROXYSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMULATORCONTROLSOAPPROXYSERVICE_EXCEPTION;
    private final static QName SIMULATORCONTROLSOAPPROXYSERVICE_QNAME = new QName("http://soap.control.globaltester.hjp.com/", "SimulatorControlSoapProxyService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/globaltester/simulatorSampleService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMULATORCONTROLSOAPPROXYSERVICE_WSDL_LOCATION = url;
        SIMULATORCONTROLSOAPPROXYSERVICE_EXCEPTION = e;
    }

    public SimulatorControlSoapProxyService() {
        super(__getWsdlLocation(), SIMULATORCONTROLSOAPPROXYSERVICE_QNAME);
    }

    public SimulatorControlSoapProxyService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMULATORCONTROLSOAPPROXYSERVICE_QNAME, features);
    }

    public SimulatorControlSoapProxyService(URL wsdlLocation) {
        super(wsdlLocation, SIMULATORCONTROLSOAPPROXYSERVICE_QNAME);
    }

    public SimulatorControlSoapProxyService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMULATORCONTROLSOAPPROXYSERVICE_QNAME, features);
    }

    public SimulatorControlSoapProxyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimulatorControlSoapProxyService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimulatorControlSoapProxy
     */
    @WebEndpoint(name = "SimulatorControlSoapProxyPort")
    public SimulatorControlSoapProxy getSimulatorControlSoapProxyPort() {
        return super.getPort(new QName("http://soap.control.globaltester.hjp.com/", "SimulatorControlSoapProxyPort"), SimulatorControlSoapProxy.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimulatorControlSoapProxy
     */
    @WebEndpoint(name = "SimulatorControlSoapProxyPort")
    public SimulatorControlSoapProxy getSimulatorControlSoapProxyPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.control.globaltester.hjp.com/", "SimulatorControlSoapProxyPort"), SimulatorControlSoapProxy.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMULATORCONTROLSOAPPROXYSERVICE_EXCEPTION!= null) {
            throw SIMULATORCONTROLSOAPPROXYSERVICE_EXCEPTION;
        }
        return SIMULATORCONTROLSOAPPROXYSERVICE_WSDL_LOCATION;
    }

}
