
package com.hjp.globaltester.control.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapServiceProviderService", targetNamespace = "http://soap.control.globaltester.hjp.com/", wsdlLocation = "http://localhost:8888/globaltester/control?wsdl")
public class SoapServiceProviderService
    extends Service
{

    private final static URL SOAPSERVICEPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPSERVICEPROVIDERSERVICE_EXCEPTION;
    private final static QName SOAPSERVICEPROVIDERSERVICE_QNAME = new QName("http://soap.control.globaltester.hjp.com/", "SoapServiceProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/globaltester/control?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPSERVICEPROVIDERSERVICE_WSDL_LOCATION = url;
        SOAPSERVICEPROVIDERSERVICE_EXCEPTION = e;
    }

    public SoapServiceProviderService() {
        super(__getWsdlLocation(), SOAPSERVICEPROVIDERSERVICE_QNAME);
    }

    public SoapServiceProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPSERVICEPROVIDERSERVICE_QNAME, features);
    }

    public SoapServiceProviderService(URL wsdlLocation) {
        super(wsdlLocation, SOAPSERVICEPROVIDERSERVICE_QNAME);
    }

    public SoapServiceProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPSERVICEPROVIDERSERVICE_QNAME, features);
    }

    public SoapServiceProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapServiceProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapServiceProvider
     */
    @WebEndpoint(name = "SoapServiceProviderPort")
    public SoapServiceProvider getSoapServiceProviderPort() {
        return super.getPort(new QName("http://soap.control.globaltester.hjp.com/", "SoapServiceProviderPort"), SoapServiceProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapServiceProvider
     */
    @WebEndpoint(name = "SoapServiceProviderPort")
    public SoapServiceProvider getSoapServiceProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.control.globaltester.hjp.com/", "SoapServiceProviderPort"), SoapServiceProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPSERVICEPROVIDERSERVICE_EXCEPTION!= null) {
            throw SOAPSERVICEPROVIDERSERVICE_EXCEPTION;
        }
        return SOAPSERVICEPROVIDERSERVICE_WSDL_LOCATION;
    }

}
